# Rename the app name before deploying: fly launch --copy-config --no-deploy
app = "meet60-server-yourname"

[build]
  dockerfile = "server/Dockerfile"

[env]
  PORT = "3001"

[[services]]
  internal_port = 3001
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
